set -g default-terminal "screen-256color"


set-option -sa terminal-features ',xterm-256color:RGB'

set -g mode-keys vi
set -g status-keys vi

#panes
set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=gray'

#status
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=blue'

set -g status-left ''

set -g status-left-length 10

set -g status-right-style 'fg=black bg=colour6'
set -g status-right ' %Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=colour6'

setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=blue bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=blue bold'


# messages
set -g message-style 'fg=yellow bg=blue bold'

# prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

